name = "checkin"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# ============================================================
# Cloudflare D1 数据库配置
# ============================================================
[[d1_databases]]
binding = "DB"
database_name = "daka-db"
database_id = "6924b928-9984-4dd8-ab00-9ea22d4c71c6"

# ============================================================
# （预留接口）后期如果需要接入 R2 对象存储存放海量原图，解开以下注释即可
# ============================================================
# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "daka-media"
